Repository real-world-study/realworld, pull requests merged in 2021-09, with the labels that each got.

#28 [DolphaGo-issue25] Add Json Web Token
  realworld-api/.gitignore
  realworld-api/build.gradle
  realworld-api/request/join.http
  realworld-api/request/login.http
  realworld-api/request/update.http
  realworld-api/src/main/java/com/study/realworld/configuration/JwtSecurityConfig.java
  realworld-api/src/main/java/com/study/realworld/configuration/WebConfig.java
  realworld-api/src/main/java/com/study/realworld/configuration/WebSecurityConfig.java
  realworld-api/src/main/java/com/study/realworld/configuration/YamlEnvironmentPostProcessor.java
  realworld-api/src/main/java/com/study/realworld/user/controller/UserController.java
  realworld-api/src/main/java/com/study/realworld/user/controller/dto/request/JoinDto.java
  realworld-api/src/main/java/com/study/realworld/user/controller/dto/request/LoginDto.java
  realworld-api/src/main/java/com/study/realworld/user/controller/dto/request/UpdateDto.java
  realworld-api/src/main/java/com/study/realworld/user/controller/dto/response/UserInfo.java
  realworld-api/src/main/java/com/study/realworld/user/jwt/JwtAccessDeniedHandler.java
  realworld-api/src/main/java/com/study/realworld/user/jwt/JwtAuthenticationEntryPoint.java
  realworld-api/src/main/java/com/study/realworld/user/jwt/JwtFilter.java
  realworld-api/src/main/java/com/study/realworld/user/jwt/JwtService.java
  realworld-api/src/main/java/com/study/realworld/user/jwt/TokenProvider.java
  realworld-api/src/main/java/com/study/realworld/user/service/UserService.java
  realworld-api/src/main/resources/META-INF/spring.factories
  realworld-api/src/main/resources/application.yml
  realworld-api/src/test/java/com/study/realworld/RealWorldApplicationTest.java
  realworld-api/src/test/java/com/study/realworld/user/controller/UserControllerTest.java
  realworld-api/src/test/java/com/study/realworld/user/controller/dto/request/JoinDtoTest.java
  realworld-api/src/test/java/com/study/realworld/user/controller/dto/request/LoginDtoTest.java
  realworld-api/src/test/java/com/study/realworld/user/jwt/JwtAccessDeniedHandlerTest.java
  realworld-api/src/test/java/com/study/realworld/user/jwt/JwtAuthenticationEntryPointTest.java
  realworld-api/src/test/java/com/study/realworld/user/jwt/JwtFilterTest.java
  realworld-api/src/test/java/com/study/realworld/user/jwt/JwtServiceTest.java
  realworld-api/src/test/java/com/study/realworld/user/jwt/TokenProviderTest.java
  realworld-api/src/test/java/com/study/realworld/user/service/UserServiceTest.java
  realworld-core/src/main/java/com/study/realworld/user/entity/User.java
  realworld-support/build.gradle
  realworld-support/src/main/java/com/study/realworld/exception/CustomException.java
  realworld-support/src/main/java/com/study/realworld/exception/ErrorCode.java
  realworld-support/src/main/java/com/study/realworld/exception/ErrorResponse.java
  realworld-support/src/main/java/com/study/realworld/exception/GlobalExceptionHandler.java
  realworld-support/src/main/java/com/study/realworld/util/CurrentUserEmail.java
  realworld-support/src/main/java/com/study/realworld/util/SecurityUtil.java
  realworld-support/src/main/java/com/study/realworld/util/TokenGenerator.java
  realworld-support/src/main/resources/application.yml
  realworld-support/src/test/java/com/study/realworld/util/SecurityUtilTest.java
Labels: DolphaGo

#26 [hoony-lab-issue23] authentication: jwt token 기능
  build.gradle
  src/main/java/com/study/realworld/config/SecurityConfig.java
  src/main/java/com/study/realworld/config/auth/JwtAuthenticationFilter.java
  src/main/java/com/study/realworld/config/auth/JwtProvider.java
  src/main/java/com/study/realworld/user/service/UserService.java
  src/main/java/com/study/realworld/user/web/UserController.java
  src/main/resources/application.yml
  src/test/java/com/study/realworld/config/auth/JwtAuthenticationFilterTest.java
  src/test/java/com/study/realworld/config/auth/JwtProviderTest.java
  src/test/java/com/study/realworld/user/service/UserServiceTest.java
  src/test/java/com/study/realworld/user/web/UserControllerTest.java
Labels: hoony-lab

#35 [chance0523-issue32] jwt 구현
  build.gradle
  src/main/java/com/study/realworld/core/configuration/JwtSecurityConfig.java
  src/main/java/com/study/realworld/core/configuration/SecurityConfig.java
  src/main/java/com/study/realworld/core/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/study/realworld/core/jwt/JwtAuthentication.java
  src/main/java/com/study/realworld/core/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/study/realworld/core/jwt/JwtFilter.java
  src/main/java/com/study/realworld/core/jwt/TokenProvider.java
  src/main/java/com/study/realworld/user/presentation/UserController.java
  src/main/java/com/study/realworld/user/presentation/model/UserResponse.java
  src/main/resources/application.yml
  src/test/java/com/study/realworld/core/jwt/JwtAccessDeniedHandlerTest.java
  src/test/java/com/study/realworld/core/jwt/JwtAuthenticationEntryPointTest.java
  src/test/java/com/study/realworld/core/jwt/JwtFilterTest.java
  src/test/java/com/study/realworld/core/jwt/TokenProviderTest.java
  src/test/java/com/study/realworld/user/presentation/UserControllerTest.java
Labels: chance

#50 [jinyoungchoi95-issue43] Exception handling 및 refactoring
  CODEOWNERS
  src/main/java/com/study/realworld/global/config/WebSecurityConfig.java
  src/main/java/com/study/realworld/global/exception/BusinessException.java
  src/main/java/com/study/realworld/global/exception/ErrorCode.java
  src/main/java/com/study/realworld/global/exception/ErrorResponse.java
  src/main/java/com/study/realworld/global/exception/GlobalExceptionHandler.java
  src/main/java/com/study/realworld/global/exception/JwtException.java
  src/main/java/com/study/realworld/security/JjwtService.java
  src/main/java/com/study/realworld/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/study/realworld/security/JwtAuthenticationTokenFilter.java
  src/main/java/com/study/realworld/security/JwtExceptionFilter.java
  src/main/java/com/study/realworld/user/controller/UserController.java
  src/main/java/com/study/realworld/user/controller/request/UserJoinRequest.java
  src/main/java/com/study/realworld/user/controller/request/UserLoginRequest.java
  src/main/java/com/study/realworld/user/controller/request/UserUpdateRequest.java
  src/main/java/com/study/realworld/user/controller/response/UserResponse.java
  src/main/java/com/study/realworld/user/domain/Bio.java
  src/main/java/com/study/realworld/user/domain/Email.java
  src/main/java/com/study/realworld/user/domain/Image.java
  src/main/java/com/study/realworld/user/domain/Password.java
  src/main/java/com/study/realworld/user/domain/User.java
  src/main/java/com/study/realworld/user/domain/Username.java
  src/main/java/com/study/realworld/user/service/UserService.java
  src/main/java/com/study/realworld/user/service/model/UserUpdateModel.java
  src/test/java/com/study/realworld/global/exception/ErrorResponseTest.java
  src/test/java/com/study/realworld/security/JjwtServiceTest.java
  src/test/java/com/study/realworld/security/JwtAuthenticationEntiyPointTest.java
  src/test/java/com/study/realworld/security/JwtAuthenticationTokenFilterTest.java
  src/test/java/com/study/realworld/security/JwtExceptionFilterTest.java
  src/test/java/com/study/realworld/user/controller/UserControllerFailTest.java
  src/test/java/com/study/realworld/user/controller/UserControllerTest.java
  src/test/java/com/study/realworld/user/controller/response/UserResponseTest.java
  src/test/java/com/study/realworld/user/domain/BioTest.java
  src/test/java/com/study/realworld/user/domain/EmailTest.java
  src/test/java/com/study/realworld/user/domain/ImageTest.java
  src/test/java/com/study/realworld/user/domain/PasswordTest.java
  src/test/java/com/study/realworld/user/domain/UserTest.java
  src/test/java/com/study/realworld/user/domain/UsernameTest.java
  src/test/java/com/study/realworld/user/service/UserServiceTest.java
Labels: feature, ori

#39 [chance0523-issue36] 현재 로그인된 유저의 정보 조회 API
  build.gradle
  src/main/java/com/study/realworld/core/util/SecurityUtils.java
  src/main/java/com/study/realworld/user/application/UserService.java
  src/main/java/com/study/realworld/user/presentation/UserController.java
  src/test/java/com/study/realworld/core/util/SecurityUtilsTest.java
  src/test/java/com/study/realworld/user/application/UserServiceTest.java
  src/test/java/com/study/realworld/user/presentation/UserControllerTest.java
Labels: chance, user
